[tool.poetry]
name = "tap-canny"
version = "0.0.1"
description = "`tap-canny` is a Singer tap for Canny, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
  "ELT",
  "singer.io",
  "Canny",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-canny"
repository = "https://github.com/edgarrmondragon/tap-canny"
documentation = "https://github.com/edgarrmondragon/tap-canny#readme"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "~=0.31.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
singer-sdk = {extras = ["testing"], version = "0.31.1"}

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
use_parentheses = true
include_trailing_comma = true
src_paths = "tap_canny"
known_first_party = "tap_canny"
add_imports = [
  "from __future__ import annotations",
]

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["backoff.*"]

[build-system]
requires = ["poetry-core>=1,<2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
"tap-canny" = "tap_canny.tap:TapCanny.cli"

[tool.ruff]
ignore = [
  "ANN101", # missing-type-self
  "DJ", # flake8-django
]
line-length = 88
select = ["ALL"]
src = ["tap_canny", "tests"]
target-version = "py37"

[tool.ruff.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201", # missing-return-type-public-function
  "S101", # assert
  "SLF001", # private-member-access
]

[tool.ruff.isort]
known-first-party = ["tap_canny"]

[tool.ruff.pydocstyle]
convention = "google"
