[tool.poetry]
name = "tap-canny"
version = "0.0.1"
description = "`tap-canny` is a Singer tap for Canny, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
  "ELT",
  "singer.io",
  "Canny",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-canny"
repository = "https://github.com/edgarrmondragon/tap-canny"
documentation = "https://github.com/edgarrmondragon/tap-canny#readme"

[tool.poetry.dependencies]
python = ">=3.8,<4"
singer-sdk = "~=0.33.0"

[tool.poetry.group.dev.dependencies]
pytest = "~=7.4"
singer-sdk = {extras = ["testing"], version = "~=0.33.0"}

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["backoff.*"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core<2,>=1",
]

[tool.poetry.scripts]
# CLI declaration
"tap-canny" = "tap_canny.tap:TapCanny.cli"

[tool.ruff]
line-length = 88
src = ["tap_canny", "tests"]
target-version = "py38"

[tool.ruff.lint]
ignore = [
  "ANN101", # missing-type-self
  "DJ", # flake8-django
  "COM812",  # missing-trailing-comma
  "ISC001",  # single-line-implicit-string-concatenation
]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201", # missing-return-type-public-function
  "S101", # assert
  "SLF001", # private-member-access
]

[tool.ruff.lint.isort]
known-first-party = ["tap_canny"]

[tool.ruff.lint.pydocstyle]
convention = "google"
